name: chatapp
description: CodeBrains Chat – Flutter app (Android)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.2.1
  flutter_highlight: ^0.7.0  # ✅ downgrade to stable version
  highlight: ^0.7.0
  shared_preferences: ^2.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
